services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - echo-postgres
      - echo-redis
    environment:
      - DB_HOST=echo-postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=echome
      # Redis
      - REDIS_HOST=echo-redis
      - REDIS_PORT=6379

      # JWT
      - JWT_SECRET=208367c61cfa6e30c2b4961e3d960a1aa69778ae26b335dd4209693d0da3c3e0

      # Server
      - PORT=5000

      # Cloudinary
      - CLOUDINARY_CLOUD_NAME=du2dpjc7v
      - CLOUDINARY_API_KEY=128119489815387
      - CLOUDINARY_API_SECRET=L4j5PA9oKbIICdlT44kO8Sz3HLI

      # AssemblyAI
      - ASSEMBLYAI_API_KEY=94d197829e944879a21422871d49897a

      # Gemini
      - GEMINI_API_KEY=AIzaSyA-gD--_PIUYBtGWwZnwhQTJxgYLq6lfCM

  echo-postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=echome
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  echo-redis:
    image: redis:7-alpine
  
  frontend:
    build: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # API URL (backend)
      - NEXT_PUBLIC_API_URL=http://localhost:5000
